# Collector specific configuration
dataset_name: "cod-ps-global"
dataset_title: "Global Subnational Population Statistics"

tags:
  - "baseline population"
  - "sex and age disaggregated data-sadd"

hxl_tags:
  "ISO3": "#country+code"
  "Country": "#country+name"
  "ADM1_PCODE": "#adm1+code"
  "ADM1_NAME": "#adm1+name"
  "ADM2_PCODE": "#adm2+code"
  "ADM2_NAME": "#adm2+name"
  "ADM3_PCODE": "#adm3+code"
  "ADM3_NAME": "#adm3+name"
  "ADM4_PCODE": "#adm4+code"
  "ADM4_NAME": "#adm4+name"
  "Population_group": "#population+group"
  "Gender": "#gender"
  "Age_range": "#age+range"
  "Age_min": "#age+min"
  "Age_max": "#age+max"
  "Population": "#population"
  "Reference_year": "#date+year"
  "Source": "#meta+source"
  "Contributor": "#meta+contributor"

encoding_exceptions:
  "ago_admpop_adm2_2024.csv": "latin-1"
  "caf_admpop_adm1_2015_v2.csv": "latin-1"
  "caf_admpop_adm2_2015_v2.csv": "latin-1"
  "caf_admpop_adm3_2015_v2.csv": "latin-1"
  "kyrgyzstan_population_statistics_2018_adm1_v2.csv": "latin-1"
  "kyrgyzstan_population_statistics_2018_adm2_v2.csv": "latin-1"

reference_year_exceptions:
  "fsm_pplp_adm0_country_v2.csv": 2010
  "fsm_pplp_adm1_state_v2.csv": 2010
  "fsm_pplp_adm2_municipality_v2.csv": 2010
  "som_pplp_adm0_v2.csv": 2014
  "som_pplp_adm1_v2.csv": 2014
  "som_pplp_adm2_v2.csv": 2014

non_latin_alphabets:
  - "ar"
  - "bg"
  - "da"
  - "el"
  - "fa"
  - "ka"
  - "ky"
  - "lo"
  - "mn"
  - "ru"
  - "si"
  - "ta"
  - "th"
  - "ua"
  - "vi"
