# Collector specific configuration
dataset_name: "cod-ps-global"
dataset_title: "OCHA Global Subnational Population Statistics"

hapi_dataset_name: "hdx-hapi-population-test"
hapi_dataset_title: "HDX HAPI - Geography & Infrastructure: Baseline Population"
hapi_resource_name: "Global Geography & Infrastructure: Baseline Population"
hapi_resource_description: "Baseline Population data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/population_and_socio-economy/#baseline-population) for more information"

tags:
  - "baseline population"
  - "sex and age disaggregated data-sadd"

hxl_tags:
  "ISO3": "#country+code"
  "Country": "#country+name"
  "ADM1_PCODE": "#adm1+code"
  "ADM1_NAME": "#adm1+name"
  "ADM2_PCODE": "#adm2+code"
  "ADM2_NAME": "#adm2+name"
  "ADM3_PCODE": "#adm3+code"
  "ADM3_NAME": "#adm3+name"
  "ADM4_PCODE": "#adm4+code"
  "ADM4_NAME": "#adm4+name"
  "Population_group": "#population+group"
  "Gender": "#gender"
  "Age_range": "#age+range"
  "Age_min": "#age+min"
  "Age_max": "#age+max"
  "Population": "#population"
  "Reference_year": "#date+year"
  "Source": "#meta+source"
  "Contributor": "#meta+contributor"

hapi_hxl_tags:
  location_code: "#country+code"
  has_hrp: "#meta+has_hrp"
  in_gho: "#meta+in_gho"
  provider_admin1_name: "#adm1+name+provider"
  provider_admin2_name: "#adm2+name+provider"
  admin1_code: "#adm1+code"
  admin1_name: "#adm1+name"
  admin2_code: "#adm2+code"
  admin2_name: "#adm2+name"
  admin_level: "#adm+level"
  gender: "#gender+code"
  age_range: "#age+range"
  min_age: "#age+min"
  max_age: "#age+max"
  population: "#population"
  reference_period_start: "#date+start"
  reference_period_end: "#date+end"
  dataset_id: "#meta+dataset_id"
  resource_id: "#meta+resource_id"
  warning: "#meta+warning"
  error: "#meta+error"

encoding_exceptions:
  "ago_admpop_adm2_2024.csv": "latin-1"
  "caf_admpop_adm1_2015_v2.csv": "latin-1"
  "caf_admpop_adm2_2015_v2.csv": "latin-1"
  "caf_admpop_adm3_2015_v2.csv": "latin-1"
  "kyrgyzstan_population_statistics_2018_adm1_v2.csv": "latin-1"
  "kyrgyzstan_population_statistics_2018_adm2_v2.csv": "latin-1"

reference_year_exceptions:
  "fsm_pplp_adm0_country_v2.csv": 2010
  "fsm_pplp_adm1_state_v2.csv": 2010
  "fsm_pplp_adm2_municipality_v2.csv": 2010
  "som_pplp_adm0_v2.csv": 2014
  "som_pplp_adm1_v2.csv": 2014
  "som_pplp_adm2_v2.csv": 2014

non_latin_alphabets:
  - "ar"
  - "bg"
  - "da"
  - "el"
  - "fa"
  - "ka"
  - "ky"
  - "lo"
  - "mn"
  - "ru"
  - "si"
  - "ta"
  - "th"
  - "ua"
  - "vi"

known_errors:
  - "CAF missing unexpected admin levels: [0, 4]"
  - "GMB missing unexpected admin levels: [0, 2, 3, 4]"
  - "KGZ missing unexpected admin levels: [0, 3, 4]"
  - "MAR missing unexpected admin levels: [0, 1, 3, 4]"
  - "POL missing unexpected admin levels: [0, 3, 4]"
